#include "PCH.h"
#include "BehaviorFileInterceptor.h"
#include "BehaviorGenerator.h"
#include "BehaviorPatcher.h"
#include "ERMemoryStream.h"

#include <mutex>

namespace EngineRelay::BehaviorFileInterceptor {

// =============================================================================
// BSResource::LooseFileLocation::DoCreateStream hook
//
// Every HKX file the game loads flows through DoCreateStream on LooseFileLocation.
// Patching vtable slot 3 lets us intercept switchboard HKX opens and serve Havok
// a ERMemoryStream wrapping the dynamically-generated bytes — no disk I/O.
//
// Generation is LAZY: the first time the hook sees a switchboard filename it calls
// BehaviorGenerator::GenerateBytes() synchronously via std::call_once.
// This fires at exactly the right moment — when Havok is about to open the file
// — regardless of SKSE message timing.
//
// If there are no registrations or generation fails, we fall through to the
// deployed fallback so the game always has a valid file.
//
// Supported switchboards (one entry per creature type):
//   "enginerelay.hkx"        → "EngineRelay.hkb"        (player/human)
//   "dragonenginerelay.hkx"  → "DragonEngineRelay.hkb"  (dragon NPCs)
// =============================================================================

using DoCreateStream_t = RE::BSResource::ErrorCode(*)(
    RE::BSResource::LooseFileLocation*,
    const char*,
    RE::BSTSmartPointer<RE::BSResource::Stream>&,
    RE::BSResource::Location*&,
    bool);

static DoCreateStream_t s_origDoCreateStream = nullptr;

// ---------------------------------------------------------------------------
// Per-switchboard state — one set of statics per supported creature type.
// std::once_flag is not copyable, so we keep separate named statics rather
// than a table of structs.
// ---------------------------------------------------------------------------

// ── Human / player ──────────────────────────────────────────────────────────
static constexpr std::string_view kHumanFilename  = "enginerelay.hkx";
static constexpr std::string_view kHumanGraphName = "EngineRelay.hkb";

static std::once_flag             s_generateOnce_human;
static std::atomic<bool>          s_armed_human{ false };
static std::vector<std::uint8_t>  s_bytes_human;

// ── Dragon ───────────────────────────────────────────────────────────────────
static constexpr std::string_view kDragonFilename  = "dragonenginerelay.hkx";
static constexpr std::string_view kDragonGraphName = "DragonEngineRelay.hkb";

static std::once_flag             s_generateOnce_dragon;
static std::atomic<bool>          s_armed_dragon{ false };
static std::vector<std::uint8_t>  s_bytes_dragon;

// ---------------------------------------------------------------------------
// Generic intercept helper — called once the filename has been matched.
// Runs generation exactly once (call_once), then serves the in-memory bytes.
// ---------------------------------------------------------------------------

static RE::BSResource::ErrorCode InterceptSwitchboard(
    RE::BSResource::LooseFileLocation*           a_this,
    const char*                                  a_path,
    RE::BSTSmartPointer<RE::BSResource::Stream>& a_stream,
    RE::BSResource::Location*&                   a_location,
    bool                                         a_readOnly,
    std::string_view                             graphName,
    std::once_flag&                              generateOnce,
    std::atomic<bool>&                           armed,
    std::vector<std::uint8_t>&                   bytes)
{
    std::call_once(generateOnce, [&]() {
        LOG_INFO("BehaviorFileInterceptor: first intercept of '{}' — "
                 "triggering lazy generation for '{}'.", a_path, graphName);

        std::vector<Registration> regs;
        for (const auto& r : BehaviorPatcher::GetRegistrations()) {
            if (r.graphName == graphName)
                regs.push_back(r);
        }

        bytes = BehaviorGenerator::GenerateBytes(regs, graphName);

        if (bytes.empty()) {
            LOG_INFO("BehaviorFileInterceptor: no bytes generated for '{}' — "
                     "will use deployed HKX.", graphName);
            return;
        }

        armed.store(true, std::memory_order_release);
        LOG_INFO("BehaviorFileInterceptor: {} bytes generated for '{}' — "
                 "in-memory redirect armed.", bytes.size(), graphName);
    });

    if (armed.load(std::memory_order_acquire)) {
        LOG_INFO("BehaviorFileInterceptor: serving '{}' from memory ({} bytes).",
            a_path, bytes.size());
        a_stream   = RE::BSTSmartPointer<RE::BSResource::Stream>{ new ERMemoryStream(bytes) };
        a_location = a_this;
        return RE::BSResource::ErrorCode::kNone;
    }

    LOG_INFO("BehaviorFileInterceptor: '{}' — using deployed HKX.", a_path);
    return s_origDoCreateStream(a_this, a_path, a_stream, a_location, a_readOnly);
}

// ---------------------------------------------------------------------------
// Hook entry point
// ---------------------------------------------------------------------------

static RE::BSResource::ErrorCode Hook_DoCreateStream(
    RE::BSResource::LooseFileLocation* a_this,
    const char*                        a_path,
    RE::BSTSmartPointer<RE::BSResource::Stream>& a_stream,
    RE::BSResource::Location*&         a_location,
    bool                               a_readOnly)
{
    if (a_path) {
        // Extract the filename component (everything after the last \ or /).
        const std::string_view fullPath(a_path);
        const auto sep      = fullPath.find_last_of("\\/");
        const auto filename = (sep != std::string_view::npos)
                                  ? fullPath.substr(sep + 1)
                                  : fullPath;

        if (_stricmp(filename.data(), kHumanFilename.data()) == 0) {
            return InterceptSwitchboard(a_this, a_path, a_stream, a_location, a_readOnly,
                kHumanGraphName, s_generateOnce_human, s_armed_human, s_bytes_human);
        }

        if (_stricmp(filename.data(), kDragonFilename.data()) == 0) {
            return InterceptSwitchboard(a_this, a_path, a_stream, a_location, a_readOnly,
                kDragonGraphName, s_generateOnce_dragon, s_armed_dragon, s_bytes_dragon);
        }

        const auto dot = fullPath.rfind('.');
        if (dot != std::string_view::npos &&
            _stricmp(fullPath.data() + dot, ".hkx") == 0) {
            LOG_DEBUG("BehaviorFileInterceptor: DoCreateStream .hkx '{}'.", a_path);
        }
    }

    return s_origDoCreateStream(a_this, a_path, a_stream, a_location, a_readOnly);
}

// =============================================================================
// Public API
// =============================================================================

void Install()
{
    REL::Relocation<std::uintptr_t> vtbl{ RE::VTABLE_BSResource__LooseFileLocation[0] };
    s_origDoCreateStream = reinterpret_cast<DoCreateStream_t>(
        vtbl.write_vfunc(3, &Hook_DoCreateStream));

    LOG_INFO("BehaviorFileInterceptor: DoCreateStream hook installed "
             "(original @ {:p}). Watching: '{}', '{}'.",
             reinterpret_cast<void*>(s_origDoCreateStream),
             kHumanFilename, kDragonFilename);
}


}  // namespace EngineRelay::BehaviorFileInterceptor
