// HkxBsbWriter.cpp — Native Havok packfile writer for BehaviorSwitchboard.hkx
//
// Binary format verified by hex-analysis of the actual compiled baseline HKX
// cross-referenced against HKX2E autogenerated class definitions.
//
// Skyrim SE packfile (64-bit LE, FileVersion=8):
//   Header        64 bytes
//   __classnames__ section: variable, 12 base entries + 2 if N>0 regs
//   __types__    : 0 bytes (empty section, shares AbsDataStart with __data__)
//   __data__     : object bodies + local data, then fixup tables
//
// Serialization order (pre-order DFS, matches vanilla HKX2E output):
//   hkRootLevelContainer
//   hkbBehaviorGraph
//   hkbStateMachine
//   hkbStateMachineStateInfo  × (N+1)  [IdleState first, then registered]
//   hkbClipGenerator          (BSB_Idle)
//   hkbBehaviorReferenceGenerator × N  [one per registration]
//   hkbBehaviorGraphData
//   hkbVariableValueSet
//   hkbBehaviorGraphStringData
//   hkbStateMachineTransitionInfoArray  (only if N>0)
//
// Key layout rules confirmed from binary analysis:
//   • hkRootLevelContainer has NO hkReferencedObject header — just array(ptr+size+cap)
//   • All other hkReferencedObject subclasses: vtable(8)+memSize(2)+refCount(2)+pad(4) = 16 bytes first
//   • After each object body, pad to 16-byte alignment before writing local data
//   • WriteVoidArray: ptr(8)=0 + size(4)=0 + cap(4)=0x80000000
//   • MODE_LOOPING = 1  (not 2)
//   • VirtualFixup.clsNameOff = offset of the name-string (after sig+sep) in __classnames__
//   • GlobalFixup.dstSec = 2 (__data__ section index)

#include "PCH.h"
#include "HkxBsbWriter.h"

namespace BehaviorSwitchboard::HkxBsbWriter {

// =============================================================================
// Byte-buffer writer
// =============================================================================
struct BufWriter {
    std::vector<std::uint8_t> buf;

    std::uint32_t pos() const { return static_cast<std::uint32_t>(buf.size()); }

    void u8 (std::uint8_t  v) { buf.push_back(v); }
    void u16(std::uint16_t v) { buf.push_back(v & 0xFF); buf.push_back((v >> 8) & 0xFF); }
    void i16(std::int16_t  v) { u16(static_cast<std::uint16_t>(v)); }
    void u32(std::uint32_t v) {
        buf.push_back( v        & 0xFF);
        buf.push_back((v >>  8) & 0xFF);
        buf.push_back((v >> 16) & 0xFF);
        buf.push_back((v >> 24) & 0xFF);
    }
    void i32(std::int32_t  v) { u32(static_cast<std::uint32_t>(v)); }
    void u64(std::uint64_t v) { u32(static_cast<std::uint32_t>(v)); u32(static_cast<std::uint32_t>(v >> 32)); }
    void f32(float v)         { std::uint32_t b; std::memcpy(&b, &v, 4); u32(b); }

    void zeros(std::uint32_t n) { buf.insert(buf.end(), n, 0x00); }
    void bytes(const void* p, std::uint32_t n) {
        const auto* bp = static_cast<const std::uint8_t*>(p);
        buf.insert(buf.end(), bp, bp + n);
    }
    void cstr(const char* s) { while (*s) buf.push_back(static_cast<std::uint8_t>(*s++)); buf.push_back(0); }

    // Pad to next multiple of 'a'
    void align(std::uint32_t a) {
        const std::uint32_t rem = pos() % a;
        if (rem) zeros(a - rem);
    }

    bool save(const std::filesystem::path& path) const {
        std::ofstream f(path, std::ios::out | std::ios::binary | std::ios::trunc);
        if (!f) return false;
        f.write(reinterpret_cast<const char*>(buf.data()),
                static_cast<std::streamsize>(buf.size()));
        return f.good();
    }
};

// =============================================================================
// Fixup entry types
// =============================================================================
struct LocalFixup  { std::uint32_t src, dst; };
struct GlobalFixup { std::uint32_t src, dstSec, dst; };
struct VirtualFixup{ std::uint32_t src, dstSec, clsNameOff; };

// =============================================================================
// Classnames section
//
// Verified offsets (name-string offset within __classnames__ section):
//   hkRootLevelContainer       = 0x4B  ← ContentsClassNameSectionOffset
//   hkbBehaviorGraph           = 0x65
//   hkbStateMachine            = 0x7B
//   hkbStateMachineStateInfo   = 0x90
//   hkbClipGenerator           = 0xAE
//   hkbBehaviorGraphData       = 0xC4
//   hkbVariableValueSet        = 0xDE
//   hkbBehaviorGraphStringData = 0xF7
// (plus BRG and TIA offsets if hasRegs)
// =============================================================================
struct ClsEntry { std::uint32_t sig; const char* name; };

static constexpr ClsEntry kBaseCls[] = {
    { 0x75585EF6u, "hkClass"                       },
    { 0x5C7EA4C2u, "hkClassMember"                 },
    { 0x8A3609CFu, "hkClassEnum"                   },
    { 0xCE6F8A6Cu, "hkClassEnumItem"               },
    { 0x2772C11Eu, "hkRootLevelContainer"           },
    { 0xB1218F86u, "hkbBehaviorGraph"              },
    { 0x816C1DCBu, "hkbStateMachine"               },
    { 0x0ED7F9D0u, "hkbStateMachineStateInfo"       },
    { 0x333B85B9u, "hkbClipGenerator"              },
    { 0x095ACA5Du, "hkbBehaviorGraphData"           },
    { 0x27812D8Du, "hkbVariableValueSet"            },
    { 0xC713064Eu, "hkbBehaviorGraphStringData"     },
};
static constexpr ClsEntry kClsBRG = { 0x0FCB5423u, "hkbBehaviorReferenceGenerator"    };
static constexpr ClsEntry kClsTIA = { 0xE397B11Eu, "hkbStateMachineTransitionInfoArray" };

struct ClsNameOffs {
    std::uint32_t rlc, bg, sm, si, cg, bgd, vvs, bgsd, brg, tia;
};

static ClsNameOffs BuildClassnames(BufWriter& out, bool hasRegs)
{
    ClsNameOffs r{};
    auto writeOne = [&](const ClsEntry& e) -> std::uint32_t {
        out.u32(e.sig);
        out.u8(0x09);
        const auto nameOff = out.pos();
        out.cstr(e.name);
        return nameOff;
    };

    for (std::size_t i = 0; i < std::size(kBaseCls); ++i) {
        const auto no = writeOne(kBaseCls[i]);
        switch (i) {
            case 4: r.rlc  = no; break;
            case 5: r.bg   = no; break;
            case 6: r.sm   = no; break;
            case 7: r.si   = no; break;
            case 8: r.cg   = no; break;
            case 9: r.bgd  = no; break;
            case 10: r.vvs = no; break;
            case 11: r.bgsd= no; break;
        }
    }
    if (hasRegs) {
        r.brg = writeOne(kClsBRG);
        r.tia = writeOne(kClsTIA);
    }
    // Pad with 0xFF to 16-byte boundary (matches baseline)
    const auto rem = out.pos() % 16;
    if (rem) for (std::uint32_t i = 0; i < (16 - rem); ++i) out.u8(0xFF);
    return r;
}

// =============================================================================
// Data section field writers
// =============================================================================

// hkReferencedObject: vtable(8) + memSizeAndFlags(2) + referenceCount(2) + pad(4)
static void WriteRefObj(BufWriter& d) { d.zeros(16); }

// hkbBindable: varBindSet(8) + cachedBindables void array(16) + bool+7pad(8)
static void WriteBindable(BufWriter& d) {
    d.zeros(8);           // variableBindingSet = null
    d.zeros(8);           // cachedBindables.data = null
    d.u32(0);             // cachedBindables.size = 0
    d.u32(0x80000000u);   // cachedBindables.cap  = 0x80000000
    d.zeros(8);           // areBindablesCached(1)+7pad
}

// hkbNode: userData(8) + name_ptr(8) + id(2)+cloneState(1)+pad(1)+pad(4)
// Returns offset of the name_ptr field.
static std::uint32_t WriteNode(BufWriter& d) {
    d.u64(0);                          // userData = 0
    const auto nameOff = d.pos();
    d.zeros(8);                        // name ptr (LocalFixup target)
    d.u16(0); d.u8(0); d.u8(0); d.u32(0); // id + cloneState + pads
    return nameOff;
}

// Void array (ptr=null, size=0, cap=0x80000000)
static void WriteVoidArr(BufWriter& d) {
    d.zeros(8); d.u32(0); d.u32(0x80000000u);
}

// Class-ptr array header: ptr(8=LocalFixup) + size(4=n) + cap(4=n|0x80000000)
// Returns offset of the ptr field.
static std::uint32_t WriteArrHdr(BufWriter& d, std::uint32_t n) {
    const auto off = d.pos();
    d.zeros(8);
    d.u32(n);
    d.u32(n | 0x80000000u);
    return off;
}

// 8-byte zero ptr slot; returns its offset.
static std::uint32_t WritePtr(BufWriter& d) {
    const auto off = d.pos();
    d.zeros(8);
    return off;
}

// Write null-terminated string, then pad to 16-byte alignment; returns start offset.
static std::uint32_t WriteStr(BufWriter& d, const char* s) {
    const auto off = d.pos();
    d.cstr(s);
    d.align(16);
    return off;
}

// Sanitize a mod name for use in Havok node identifiers.
static std::string San(std::string_view name) {
    std::string out;
    out.reserve(name.size());
    for (char c : name)
        out.push_back((std::isalnum(static_cast<unsigned char>(c)) || c == '_') ? c : '_');
    if (!out.empty() && std::isdigit(static_cast<unsigned char>(out[0])))
        out.insert(out.begin(), '_');
    return out;
}

// =============================================================================
// Main writer
// =============================================================================
std::vector<std::uint8_t> WriteToMemory(const std::vector<Registration>& registrations,
                                         std::string_view                 graphName)
{
    const bool hasRegs = !registrations.empty();
    const auto N = static_cast<std::uint32_t>(registrations.size());

    // ── Classnames section ────────────────────────────────────────────────────
    BufWriter cls;
    const ClsNameOffs clsOffs = BuildClassnames(cls, hasRegs);

    // ── Data section ──────────────────────────────────────────────────────────
    BufWriter d;

    std::vector<LocalFixup>   LF;   // local fixups
    std::vector<VirtualFixup> VF;   // virtual fixups

    // GlobalFixups are built at the end once all object offsets are known.
    // During writing, we record the SRC position only.
    std::uint32_t g_rlcVariant   = 0;  // RLC NamedVariant.variant → BG
    std::uint32_t g_bgRoot       = 0;  // BG.rootGenerator → SM
    std::uint32_t g_bgData       = 0;  // BG.data → BGD
    std::uint32_t g_smWild       = 0;  // SM.wildcardTransitions → TIA (if N>0)
    std::vector<std::uint32_t> g_smStates; // SM states array slots → StateInfo[i]
    std::uint32_t g_idleSIgen    = 0;  // IdleSI.generator → IdleCG
    std::vector<std::uint32_t> g_regSIgen; // RegSI[i].generator → BRG[i]
    std::uint32_t g_bgdVVS       = 0;  // BGD.variableInitialValues → VVS
    std::uint32_t g_bgdBGSD      = 0;  // BGD.stringData → BGSD

    // Object data offsets (relative to __data__ section AbsDataStart)
    std::uint32_t off_RLC   = 0;
    std::uint32_t off_BG    = 0;
    std::uint32_t off_SM    = 0;
    std::uint32_t off_IdleSI = 0;
    std::vector<std::uint32_t> off_RegSI;
    std::uint32_t off_IdleCG = 0;
    std::vector<std::uint32_t> off_BRG;
    std::uint32_t off_BGD   = 0;
    std::uint32_t off_VVS   = 0;
    std::uint32_t off_BGSD  = 0;
    std::uint32_t off_TIA   = 0;

    // =========================================================================
    // [1] hkRootLevelContainer  (no hkReferencedObject header — just array body)
    //     Body = 16 bytes: namedVariants array ptr(8)+size(4)+cap(4)
    // =========================================================================
    off_RLC = d.pos();
    VF.push_back({off_RLC, 0, clsOffs.rlc});
    {
        const auto arrPtrOff = WritePtr(d);   // namedVariants.data ptr
        d.u32(1);                              // size = 1
        d.u32(0x80000001u);                    // cap = 1|0x80000000

        // Local data: 1 × NamedVariant (24 bytes) immediately after body.
        // (Body=16 bytes, 16%16=0 → no alignment padding needed)
        const auto arrDataOff = d.pos();
        LF.push_back({arrPtrOff, arrDataOff});

        // NamedVariant[0]
        const auto nvNamePtr  = WritePtr(d);   // name ptr → "hkbBehaviorGraph"
        const auto nvClsPtr   = WritePtr(d);   // className ptr → "hkbBehaviorGraph"
        g_rlcVariant          = WritePtr(d);   // variant ptr → BG (GlobalFixup)

        // String local data
        const auto nvNameStrOff = WriteStr(d, "hkbBehaviorGraph");
        const auto nvClsStrOff  = WriteStr(d, "hkbBehaviorGraph");
        LF.push_back({nvNamePtr, nvNameStrOff});
        LF.push_back({nvClsPtr,  nvClsStrOff});
    }
    d.align(16);

    // =========================================================================
    // [2] hkbBehaviorGraph
    //     Body = 0x130 = 304 bytes
    // =========================================================================
    off_BG = d.pos();
    VF.push_back({off_BG, 0, clsOffs.bg});
    {
        WriteRefObj(d);    // 0x00-0x0F (16)
        WriteBindable(d);  // 0x10-0x2F (32)
        const auto namePtr = WriteNode(d);  // 0x30-0x47 (24) → returns name ptr off

        // 0x48: variableMode(sbyte=0=VARIABLE_MODE_DISCARD_WHEN_INACTIVE) + 7 pad
        d.u8(0); d.zeros(7);

        // 0x50: uniqueIdPool void array
        WriteVoidArr(d);

        // 0x60: idToStateMachineTemplateMap void ptr
        d.zeros(8);

        // 0x68: mirroredExternalIdMap void array
        WriteVoidArr(d);

        // 0x78: pseudoRandomGenerator void ptr
        d.zeros(8);

        // 0x80: rootGenerator ptr → SM
        g_bgRoot = WritePtr(d);

        // 0x88: data ptr → BGD
        g_bgData = WritePtr(d);

        // 0x90-0xFF: 14 void ptrs (runtime/serialize-ignored fields)
        for (int i = 0; i < 14; ++i) d.zeros(8);

        // 0x100: numIntermediateOutputs(i32=0) + pad(4)
        d.u32(0); d.u32(0);

        // 0x108: jobs void array
        WriteVoidArr(d);

        // 0x118: allPartitionMemory void array
        WriteVoidArr(d);

        // 0x128: numStaticNodes(i16) + nextUniqueId(i16) + 4 bools + 2 pad = 8 bytes
        d.u16(0); d.u16(0); d.u8(0); d.u8(0); d.u8(0); d.u8(0);
        // TOTAL BODY = 0x130 = 304 bytes. 304 % 16 = 0, no pre-local-data padding needed.

        // Local data: BG name string
        d.align(16);  // 0%16=0 — no-op, but kept for clarity
        const std::string graphNameStr(graphName);
        const auto nameStrOff = WriteStr(d, graphNameStr.c_str());
        LF.push_back({namePtr, nameStrOff});
    }
    d.align(16);

    // =========================================================================
    // [3] hkbStateMachine
    //     Body = 0x108 = 264 bytes.  264 % 16 = 8 → 8 bytes padding before local data.
    // =========================================================================
    off_SM = d.pos();
    VF.push_back({off_SM, 0, clsOffs.sm});
    std::uint32_t sm_namePtr = 0;
    {
        WriteRefObj(d);   // 0x00-0x0F
        WriteBindable(d); // 0x10-0x2F
        sm_namePtr = WriteNode(d); // 0x30-0x47

        // 0x48: hkbEvent inline (24 bytes): id(-1) + pad(4) + payload ptr(8) + sender ptr(8)
        d.i32(-1); d.u32(0); d.zeros(8); d.zeros(8);

        // 0x60: startStateChooser ptr = null
        d.zeros(8);

        // 0x68: startStateId(i32=0)
        d.i32(0);

        // 0x6C-0x7F: returnToPrevious + random + toNextHigher + toNextLower + sync (5 × i32 = -1)
        d.i32(-1); d.i32(-1); d.i32(-1); d.i32(-1); d.i32(-1);

        // 0x80: currentStateId (serialize-ignored, i32=0)
        d.i32(0);

        // 0x84: wrapAroundStateId(bool=0) + maxSimultaneousTransitions(sbyte=32)
        //        + startStateMode(sbyte=0) + selfTransitionMode(sbyte=0)
        //        + isActive(bool=0) + 3 pad + 4 pad  = 12 bytes total to reach 0x90
        d.u8(0);    // wrapAroundStateId
        d.u8(32);   // maxSimultaneousTransitions
        d.u8(0);    // startStateMode = START_STATE_MODE_DEFAULT
        d.u8(0);    // selfTransitionMode = SELF_TRANSITION_MODE_NO_TRANSITION
        d.u8(0);    // isActive (serialize-ignored)
        d.zeros(3); // pad bytes
        d.zeros(4); // additional pad → 0x90

        // 0x90: states class ptr array (N+1 entries)
        const auto statesArrPtrOff = WriteArrHdr(d, N + 1);

        // 0xA0: wildcardTransitions class ptr
        g_smWild = WritePtr(d);

        // 0xA8: stateIdToIndexMap void ptr = null
        d.zeros(8);

        // 0xB0-0xDF: 4 void arrays (activeTransitions, transitionFlags, wildcardTransitionFlags, delayedTransitions)
        WriteVoidArr(d); WriteVoidArr(d); WriteVoidArr(d); WriteVoidArr(d);

        // 0xF0: timeInState(f) + lastLocalTime(f) + previousStateId(i32) + nextStartStateIndexOverride(i32)
        d.f32(0.0f); d.f32(0.0f); d.i32(0); d.i32(0);

        // 0x100: stateOrTransitionChanged(bool) + echoNextUpdate(bool) + sCurrentState(u16) + pad(4)
        d.u8(0); d.u8(0); d.u16(0); d.u32(0);
        // BODY = 0x108 = 264 bytes. 264 % 16 = 8 → need 8-byte padding before local data.

        // Local data
        d.align(16);  // 8 bytes padding to reach 16-byte boundary
        const auto nameStrOff = WriteStr(d, "BSB_SwitchboardSM");
        LF.push_back({sm_namePtr, nameStrOff});

        // States array data: (N+1) × 8-byte GlobalFixup slots
        const auto statesArrDataOff = d.pos();
        LF.push_back({statesArrPtrOff, statesArrDataOff});
        for (std::uint32_t i = 0; i < N + 1; ++i) {
            g_smStates.push_back(d.pos());
            d.zeros(8);
        }
        d.align(16);
    }
    d.align(16);

    // =========================================================================
    // [4] hkbStateMachineStateInfo — BSB_IdleState (stateId=0)
    //     Body = 0x78 = 120 bytes.  120 % 16 = 8 → 8-byte padding before local data.
    // =========================================================================
    off_IdleSI = d.pos();
    VF.push_back({off_IdleSI, 0, clsOffs.si});
    {
        WriteRefObj(d);
        WriteBindable(d);

        // 0x30: listeners class ptr array (empty)
        WriteArrHdr(d, 0);

        // 0x40: enterNotifyEvents ptr = null
        d.zeros(8);
        // 0x48: exitNotifyEvents ptr = null
        d.zeros(8);
        // 0x50: transitions ptr = null
        d.zeros(8);

        // 0x58: generator ptr → hkbClipGenerator
        g_idleSIgen = WritePtr(d);

        // 0x60: name ptr
        const auto namePtr = WritePtr(d);

        // 0x68: stateId(i32=0) + probability(f=1.0f) + enable(bool=true) + 7 pad
        d.i32(0); d.f32(1.0f); d.u8(1); d.zeros(7);
        // BODY = 0x78 = 120 bytes. 120 % 16 = 8 → 8-byte pad.

        d.align(16);
        const auto nameStrOff = WriteStr(d, "BSB_IdleState");
        LF.push_back({namePtr, nameStrOff});
    }
    d.align(16);

    // =========================================================================
    // [5] hkbStateMachineStateInfo per registration (stateId = 1..N)
    // =========================================================================
    for (std::uint32_t i = 0; i < N; ++i) {
        const auto& reg = registrations[i];
        const auto stateName = std::string("BSB_") + San(reg.modName) + "_State";

        off_RegSI.push_back(d.pos());
        VF.push_back({d.pos(), 0, clsOffs.si});

        WriteRefObj(d);
        WriteBindable(d);
        WriteArrHdr(d, 0);  // listeners = empty
        d.zeros(8);          // enterNotifyEvents = null
        d.zeros(8);          // exitNotifyEvents  = null
        d.zeros(8);          // transitions = null

        // generator ptr → BRG[i]
        g_regSIgen.push_back(WritePtr(d));

        const auto namePtr = WritePtr(d);
        d.i32(static_cast<std::int32_t>(i + 1)); // stateId = 1-based
        d.f32(1.0f); d.u8(1); d.zeros(7);

        d.align(16);
        const auto nameStrOff = WriteStr(d, stateName.c_str());
        LF.push_back({namePtr, nameStrOff});
        d.align(16);
    }

    // =========================================================================
    // [6] hkbClipGenerator — BSB_Idle
    //     Body = 0x110 = 272 bytes.  272 % 16 = 0 → no pre-local-data padding.
    // =========================================================================
    off_IdleCG = d.pos();
    VF.push_back({off_IdleCG, 0, clsOffs.cg});
    {
        WriteRefObj(d);
        WriteBindable(d);
        const auto nodeNamePtr  = WriteNode(d);    // 0x30-0x47

        // 0x48: animationName string ptr
        const auto animNamePtr  = WritePtr(d);

        // 0x50: triggers ptr = null
        d.zeros(8);

        // 0x58-0x6F: 6 floats
        d.f32(0.0f);  // cropStartAmountLocalTime
        d.f32(0.0f);  // cropEndAmountLocalTime
        d.f32(0.0f);  // startTime
        d.f32(1.0f);  // playbackSpeed
        d.f32(0.0f);  // enforcedDuration
        d.f32(0.0f);  // userControlledTimeFraction

        // 0x70: animationBindingIndex(i16=-1) + mode(sbyte=1=MODE_LOOPING) + flags(sbyte=0) + pad(4)
        d.i16(-1);
        d.u8(1);   // MODE_LOOPING = 1
        d.u8(0);   // flags = 0
        d.u32(0);  // pad

        // 0x78: animDatas void array
        WriteVoidArr(d);

        // 0x88-0xAF: 5 void ptrs (serialize-ignored runtime fields)
        for (int i = 0; i < 5; ++i) d.zeros(8);

        // 0xB0-0xDF: QSTransform (3×4 floats = 48 bytes, all zero)
        d.zeros(48);

        // 0xE0: echos void array
        WriteVoidArr(d);

        // 0xF0: localTime(f)+time(f)+prevUserFraction(f)+bufferSize(i32)+echoBufferSize(i32)
        d.f32(0.0f); d.f32(0.0f); d.f32(0.0f); d.i32(0); d.i32(0);

        // 0x104: atEnd(bool)+ignoreStartTime(bool)+pingPongBackward(bool)+9 pad = 12 bytes
        d.u8(0); d.u8(0); d.u8(0); d.zeros(9);
        // BODY = 0x110 = 272 bytes. 272 % 16 = 0 → no padding needed.

        static constexpr const char kAnimPath[] =
            "Animations\\Cassieandstuff\\BehaviorSwitchboard\\BSB_Idle.hkx";
        d.align(16);
        const auto nodeNameStrOff = WriteStr(d, "BSB_Idle");
        const auto animNameStrOff = WriteStr(d, kAnimPath);
        LF.push_back({nodeNamePtr, nodeNameStrOff});
        LF.push_back({animNamePtr, animNameStrOff});
    }
    d.align(16);

    // =========================================================================
    // [7] hkbBehaviorReferenceGenerator per registration
    //     Body = 0x58 = 88 bytes.  88 % 16 = 8 → 8-byte pre-local-data padding.
    // =========================================================================
    for (std::uint32_t i = 0; i < N; ++i) {
        const auto& reg = registrations[i];
        const auto brgName = std::string("BSB_") + San(reg.modName) + "BRG";

        off_BRG.push_back(d.pos());
        VF.push_back({d.pos(), 0, clsOffs.brg});

        WriteRefObj(d);
        WriteBindable(d);
        const auto nodeNamePtr  = WriteNode(d);    // 0x30-0x47

        // 0x48: behaviorName string ptr
        const auto behNamePtr   = WritePtr(d);

        // 0x50: behavior void ptr (serialize-ignored) = null
        d.zeros(8);
        // BODY = 0x58 = 88 bytes. 88 % 16 = 8 → 8-byte pad.

        d.align(16);
        const auto nodeNameStrOff = WriteStr(d, brgName.c_str());
        const auto behNameStrOff  = WriteStr(d, reg.behaviorPath.c_str());
        LF.push_back({nodeNamePtr, nodeNameStrOff});
        LF.push_back({behNamePtr,  behNameStrOff});
        d.align(16);
    }

    // =========================================================================
    // [8] hkbBehaviorGraphData
    //     Body = 0x80 = 128 bytes.  128 % 16 = 0 → no pre-local-data padding.
    // =========================================================================
    off_BGD = d.pos();
    VF.push_back({off_BGD, 0, clsOffs.bgd});
    std::uint32_t bgd_evtArrPtr = 0;
    {
        WriteRefObj(d);

        // 0x10: attributeDefaults float array = empty
        WriteVoidArr(d);

        // 0x20: variableInfos class array = empty
        WriteVoidArr(d);

        // 0x30: characterPropertyInfos class array = empty
        WriteVoidArr(d);

        // 0x40: eventInfos class array (N entries)
        bgd_evtArrPtr = WriteArrHdr(d, N);

        // 0x50: wordMinVariableValues class array = empty
        WriteVoidArr(d);

        // 0x60: wordMaxVariableValues class array = empty
        WriteVoidArr(d);

        // 0x70: variableInitialValues ptr → VVS
        g_bgdVVS  = WritePtr(d);

        // 0x78: stringData ptr → BGSD
        g_bgdBGSD = WritePtr(d);
        // BODY = 0x80 = 128 bytes. 128 % 16 = 0.

        // Local data: N × hkbEventInfo (4 bytes flags=0 each)
        if (N > 0) {
            d.align(16);
            const auto evtDataOff = d.pos();
            LF.push_back({bgd_evtArrPtr, evtDataOff});
            for (std::uint32_t i = 0; i < N; ++i) d.u32(0);  // flags = 0
            d.align(16);
        }
    }
    d.align(16);

    // =========================================================================
    // [9] hkbVariableValueSet
    //     Body = 0x40 = 64 bytes. Three empty arrays.
    // =========================================================================
    off_VVS = d.pos();
    VF.push_back({off_VVS, 0, clsOffs.vvs});
    {
        WriteRefObj(d);
        WriteVoidArr(d);  // wordVariableValues
        WriteVoidArr(d);  // quadVariableValues
        WriteVoidArr(d);  // variantVariableValues
        // BODY = 0x40. No local data.
    }
    d.align(16);

    // =========================================================================
    // [10] hkbBehaviorGraphStringData
    //     Body = 0x50 = 80 bytes. Four string-ptr arrays.
    // =========================================================================
    off_BGSD = d.pos();
    VF.push_back({off_BGSD, 0, clsOffs.bgsd});
    {
        WriteRefObj(d);

        // 0x10: eventNames string ptr array (N entries)
        const auto evtNameArrPtr = WriteArrHdr(d, N);

        // 0x20: attributeNames = empty
        WriteVoidArr(d);

        // 0x30: variableNames = empty
        WriteVoidArr(d);

        // 0x40: characterPropertyNames = empty
        WriteVoidArr(d);
        // BODY = 0x50. 80 % 16 = 0.

        if (N > 0) {
            d.align(16);
            // Write the string-pointer array (N slots, each 8 bytes)
            const auto evtPtrArrOff = d.pos();
            LF.push_back({evtNameArrPtr, evtPtrArrOff});

            std::vector<std::uint32_t> evtPtrSlots;
            for (std::uint32_t i = 0; i < N; ++i) {
                evtPtrSlots.push_back(d.pos());
                d.zeros(8);
            }
            d.align(16);

            // Write each event name string
            for (std::uint32_t i = 0; i < N; ++i) {
                const auto strOff = WriteStr(d, registrations[i].eventName.c_str());
                LF.push_back({evtPtrSlots[i], strOff});
            }
        }
    }
    d.align(16);

    // =========================================================================
    // [11] hkbStateMachineTransitionInfoArray  (only if N>0)
    //     Body = 0x20 = 32 bytes.
    //     Contains N wildcard transitions.
    //     Each hkbStateMachineTransitionInfo = 72 bytes.
    // =========================================================================
    if (hasRegs) {
        off_TIA = d.pos();
        VF.push_back({off_TIA, 0, clsOffs.tia});

        WriteRefObj(d);  // 16 bytes

        // 0x10: transitions class array (N entries)
        const auto tiaArrPtr = WriteArrHdr(d, N);
        // BODY = 0x20 = 32 bytes. 32 % 16 = 0.

        // Local data: N × TransitionInfo (72 bytes each)
        d.align(16);
        const auto tiaDataOff = d.pos();
        LF.push_back({tiaArrPtr, tiaDataOff});

        for (std::uint32_t i = 0; i < N; ++i) {
            // hkbStateMachineTimeInterval × 2: enterEventId(-1)+exitEventId(-1)+enterTime+exitTime
            d.i32(-1); d.i32(-1); d.f32(0.0f); d.f32(0.0f);  // triggerInterval
            d.i32(-1); d.i32(-1); d.f32(0.0f); d.f32(0.0f);  // initiateInterval

            d.zeros(8);  // transition effect ptr = null
            d.zeros(8);  // condition ptr = null

            // eventId = i (event i corresponds to registration i's event name in BGD/BGSD)
            d.i32(static_cast<std::int32_t>(i));

            // toStateId = i+1 (state 0=idle, 1..N = registered states)
            d.i32(static_cast<std::int32_t>(i + 1));

            d.i32(0);    // fromNestedStateId = 0
            d.i32(0);    // toNestedStateId = 0
            d.i16(0);    // priority = 0

            // flags: FLAG_IS_LOCAL_WILDCARD(0x0800) | FLAG_DISABLE_CONDITION(0x0100) = 0x0900
            d.i16(static_cast<std::int16_t>(0x0900));

            d.u32(0);    // pad
            // Each entry = 72 bytes ✓
        }
        d.align(16);
    }

    // =========================================================================
    // Build GlobalFixups (all object offsets now known)
    // =========================================================================
    std::vector<GlobalFixup> GF;
    GF.reserve(4 + (N > 0 ? 1u : 0u) + (N + 1) + 1 + N + 2);

    // RLC.variant → BG
    GF.push_back({g_rlcVariant, 2, off_BG});

    // BG.rootGenerator → SM
    GF.push_back({g_bgRoot, 2, off_SM});

    // BG.data → BGD
    GF.push_back({g_bgData, 2, off_BGD});

    // SM.wildcardTransitions → TIA  (only if N>0)
    if (hasRegs)
        GF.push_back({g_smWild, 2, off_TIA});

    // SM states array: slot 0 → IdleSI, slot i+1 → RegSI[i]
    GF.push_back({g_smStates[0], 2, off_IdleSI});
    for (std::uint32_t i = 0; i < N; ++i)
        GF.push_back({g_smStates[i + 1], 2, off_RegSI[i]});

    // IdleSI.generator → IdleCG
    GF.push_back({g_idleSIgen, 2, off_IdleCG});

    // RegSI[i].generator → BRG[i]
    for (std::uint32_t i = 0; i < N; ++i)
        GF.push_back({g_regSIgen[i], 2, off_BRG[i]});

    // BGD.variableInitialValues → VVS
    GF.push_back({g_bgdVVS, 2, off_VVS});

    // BGD.stringData → BGSD
    GF.push_back({g_bgdBGSD, 2, off_BGSD});

    // =========================================================================
    // Assemble the file
    // =========================================================================
    const std::uint32_t clsSize  = cls.pos();
    const std::uint32_t dataSz   = d.pos();

    // +1 sentinel (0xFFFFFFFF...) terminates both local and global tables.
    // Virtual fixup table has no terminal entry.
    const std::uint32_t localSz  = (static_cast<std::uint32_t>(LF.size()) + 1u) * 8u;
    const std::uint32_t globalSz = (static_cast<std::uint32_t>(GF.size()) + 1u) * 12u;
    const std::uint32_t virtSz   =  static_cast<std::uint32_t>(VF.size())        * 12u;

    const std::uint32_t localOff  = dataSz;
    const std::uint32_t globalOff = localOff  + localSz;
    const std::uint32_t virtOff   = globalOff + globalSz;
    const std::uint32_t expOff    = virtOff   + virtSz;
    const std::uint32_t endOff    = expOff;  // no exports/imports

    // Absolute file positions
    constexpr std::uint32_t kFileHdrSz  = 64u;
    constexpr std::uint32_t kSecHdrSz   = 48u;
    constexpr std::uint32_t kNSections  = 3u;
    const std::uint32_t absClsStart  = kFileHdrSz + kNSections * kSecHdrSz;  // 0xD0
    const std::uint32_t absDataStart = absClsStart + clsSize;  // __types__ is empty

    BufWriter out;

    // ── File header (64 bytes) ───────────────────────────────────────────────
    static constexpr std::uint8_t kMagic[] = {
        0x57,0xE0,0xE0,0x57, 0x10,0xC0,0xC0,0x10
    };
    out.bytes(kMagic, 8);
    out.u32(0);           // UserTag = 0
    out.u32(8);           // FileVersion = 8
    out.u8(8);            // PointerSize = 8
    out.u8(1);            // Endian = 1 (little-endian)
    out.u8(0);            // PaddingOption = 0
    out.u8(1);            // BaseClass = 1
    out.u32(kNSections);  // SectionCount = 3
    out.u32(2);           // ContentsSectionIndex = 2 (__data__)
    out.u32(0);           // ContentsSectionOffset = 0 (root obj at data offset 0)
    out.u32(0);           // ContentsClassNameSectionIndex = 0 (__classnames__)
    out.u32(clsOffs.rlc); // ContentsClassNameSectionOffset = name-string offset of RLC
    // ContentsVersionString (16 bytes): "hk_2010.2.0-r1\0\xFF"
    {
        static const char kVer[] = "hk_2010.2.0-r1";  // 14 chars
        out.bytes(kVer, 15);   // 14 chars + null terminator
        out.u8(0xFF);          // 16th byte (verified from binary: 0xFF)
    }
    out.u32(0);           // Flags = 0
    out.i16(-1);          // MaxPredicate = -1 (0xFFFF)
    out.i16(-1);          // SectionOffset = -1 (0xFFFF)
    // File header = 64 bytes ✓

    // ── Section headers (3 × 48 bytes) ──────────────────────────────────────
    auto writeSecHdr = [&](const char* tag,
                            std::uint32_t absStart,
                            std::uint32_t lr, std::uint32_t gr, std::uint32_t vr,
                            std::uint32_t er, std::uint32_t ir, std::uint32_t endr)
    {
        char tb[20]{};
        std::strncpy(tb, tag, 19);
        out.bytes(tb, 19);
        out.u8(0xFF);         // separator
        out.u32(absStart);
        out.u32(lr); out.u32(gr); out.u32(vr);
        out.u32(er); out.u32(ir); out.u32(endr);
    };

    // __classnames__: no fixup tables; all offsets = clsSize (== end of section data)
    writeSecHdr("__classnames__", absClsStart,
        clsSize, clsSize, clsSize, clsSize, clsSize, clsSize);

    // __types__: empty section (shares AbsDataStart with __data__)
    writeSecHdr("__types__", absDataStart,
        0, 0, 0, 0, 0, 0);

    // __data__: fixup tables follow object data
    writeSecHdr("__data__", absDataStart,
        localOff, globalOff, virtOff, expOff, expOff, endOff);

    // ── Sections ─────────────────────────────────────────────────────────────
    out.bytes(cls.buf.data(), clsSize);   // __classnames__
    // __types__ (empty, no bytes)
    out.bytes(d.buf.data(), dataSz);      // __data__ objects

    // ── Local fixup table ────────────────────────────────────────────────────
    for (const auto& lf : LF) { out.u32(lf.src); out.u32(lf.dst); }
    out.u32(0xFFFFFFFFu); out.u32(0xFFFFFFFFu);   // terminal sentinel

    // ── Global fixup table ───────────────────────────────────────────────────
    for (const auto& gf : GF) { out.u32(gf.src); out.u32(gf.dstSec); out.u32(gf.dst); }
    out.u32(0xFFFFFFFFu); out.u32(0xFFFFFFFFu); out.u32(0xFFFFFFFFu);  // terminal sentinel

    // ── Virtual fixup table ──────────────────────────────────────────────────
    // (No terminal entry — virtual fixup table count is exact.)
    for (const auto& vf : VF) { out.u32(vf.src); out.u32(vf.dstSec); out.u32(vf.clsNameOff); }

    return std::move(out.buf);
}

bool Write(const std::vector<Registration>& registrations,
           const std::filesystem::path&     outPath,
           std::string_view                 graphName)
{
    const auto bytes = WriteToMemory(registrations, graphName);
    std::ofstream f(outPath, std::ios::out | std::ios::binary | std::ios::trunc);
    if (!f) return false;
    f.write(reinterpret_cast<const char*>(bytes.data()),
            static_cast<std::streamsize>(bytes.size()));
    return f.good();
}

}  // namespace BehaviorSwitchboard::HkxBsbWriter
