class: hkbClipGenerator
name: CLIP_Death_Agony_End
animationName: Animations\Special_AlduinDeathShattered.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: -0.133000
    event: Ragdoll
    relativeToEndOfClip: true