class: hkbClipGenerator
name: CLIP_Ground_Combat_Attack_Bite_Left
animationName: Animations\Ground_BiteLeft.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: endGroundAttack
    relativeToEndOfClip: true