class: hkbClipGenerator
name: CLIP_Flight_Default_Feather_Default_Left
animationName: Animations\MTFeatherSlow_BankLeft.HKX
mode: MODE_LOOPING
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: FlapThrustEnd
  - localTime: 0.067000
    event: FeatherBegin
  - localTime: 0.667000
    event: AllowFeatherExit_End
  - localTime: 0.668000
    event: AllowFeatherExit_Begin