class: hkbClipGenerator
name: CLIP_TakeOff_Vertical
animationName: Animations\MTTakeOffVertical.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
cropStartAmountLocalTime: 0.700000
flags: 1
triggers:
  - localTime: -1.167000
    event: TakeOff_to_WingState
    relativeToEndOfClip: true