class: hkbClipGenerator
name: CLIP_Hover_Enter_Default_Right180
animationName: Animations\MTFeatherStopRight180.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: HoverIdle
    relativeToEndOfClip: true