class: hkbClipGenerator
name: CLIP_Perch_RockL02_Roar
animationName: Animations\Special_ParthPerchRoar.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: to_Perch_Idle
    relativeToEndOfClip: true