class: hkbClipGenerator
name: CLIP_Flight_Default_Glide_Dive_Right
animationName: Animations\MTDescend_DiveBankRight.HKX
mode: MODE_LOOPING
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: FeatherEnd
  - localTime: 0.000000
    event: FlapThrustEnd