class: hkbClipGenerator
name: CLIP_Land_Crash_Approach_Right180
animationName: Animations\MTLand_CrashLongApproachRight180.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: BeginLand
    relativeToEndOfClip: true