class: hkbClipGenerator
name: CLIP_Flight_Stagger
animationName: Animations\MTFlight_HitLight.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: staggerStop
    relativeToEndOfClip: true