class: hkbClipGenerator
name: CLIP_Flight_Default_Feather_Injured_Right
animationName: Animations\MTForward_GlideHurtBankRight.HKX
mode: MODE_LOOPING
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: FlapThrustEnd
  - localTime: 0.067000
    event: FeatherBegin
  - localTime: 0.667000
    event: AllowFeatherExit_End
  - localTime: 0.667000
    event: AllowFeatherExit_Begin