class: hkbClipGenerator
name: CLIP_Land_Perch_LakeDive_Left180
animationName: Animations\DLC01\Special_WaterDiveEnterL90.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: PerchLandEnd
    relativeToEndOfClip: true