class: hkbClipGenerator
name: CLIP_Flight_Default_Glide_Default
animationName: Animations\MTForward_Glide.HKX
mode: MODE_LOOPING
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: FlapThrustEnd
  - localTime: 0.000000
    event: FeatherEnd