class: hkbClipGenerator
name: CLIP_Hover_Enter_Vertical_Right90
animationName: Animations\MTFeatherStop_VerticalRight90.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: HoverIdle
    relativeToEndOfClip: true