class: hkbClipGenerator
name: CLIP_TakeOff_Default_Ground
animationName: Animations\MTTakeOff45.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.667000
    event: to_TakeOff_Flight