class: hkbClipGenerator
name: CLIP_Land_Default_Approach_Left180
animationName: Animations\MTLand45ApproachLeft180.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: BeginLand
    relativeToEndOfClip: true