class: hkbClipGenerator
name: CLIP_Furniture_Mound_Exit
animationName: Animations\Special_ResurrectionExit.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: -0.033000
    event: IdleFurnitureExit
    relativeToEndOfClip: true