class: hkbClipGenerator
name: CLIP_Perch_Tower_Roar
animationName: Animations\Special_PerchAlduinTowerRoar.HKX
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: to_Perch_Idle
    relativeToEndOfClip: true