class: hkbClipGenerator
name: Paired_2HMKillMoveDragonSlash
animationName: ..\SharedKillMoves\Human&Dragon\Paired_2HMKillMoveDragonSlash.hkx
mode: MODE_SINGLE_PLAY
playbackSpeed: 1.000000
triggers:
  - localTime: 0.000000
    event: 2_KillMoveStart
  - localTime: 0.038000
    event: 2_SoundPlay.NPCDragonKillRoarB
  - localTime: 0.751000
    event: 2_SoundPlay.NPCDragonKillRoarA
  - localTime: 1.540000
    event: 2_SoundPlay.NPCDragonInjuredSD
  - localTime: 2.961000
    event: 2_SoundPlay.FSTDirtJumpUpSD
  - localTime: 2.994000
    event: 2_SoundPlay.NPCDragonKillRoarB
  - localTime: 4.175000
    event: 2_KillActor
  - localTime: 4.175000
    event: 2_pairedStop
  - localTime: 4.175000
    event: 2_KillMoveEnd
  - localTime: 4.175000
    event: 2_PairEnd